[package]
name = "redis-example"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring = { path = "../../spring" }
spring-web = { path = "../../spring-web" }
spring-redis = { path = "../../spring-redis" }
tokio = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }