[web]
binding = "0.0.0.0"
port = 8080
connect_info = true
graceful = true

[websocket]
# WebSocket endpoint path
endpoint = "/ws"

# Maximum number of concurrent connections
max_connections = 1000

# Maximum message size in bytes
max_message_size = 65536

# Connection idle timeout in seconds
idle_timeout = 300

# Ping interval in seconds
ping_interval = 30

# Maximum number of rooms
max_rooms = 100

# Enable message compression
compression = true

# Rate limiting configuration (optional)
[websocket.rate_limit]
messages_per_minute = 60
connections_per_ip = 10
ban_duration = 300

# Authentication configuration (optional)
[websocket.auth]
token_header = "Authorization"
jwt_secret = "your-secret-key"
token_expiry = 3600
