[package]
name = "openai-example"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring = { path = "../../spring" }
spring-web = { path = "../../spring-web" }
spring-openai = { path = "../../spring-openai" }
tokio = { workspace = true }
anyhow = { workspace = true }
