[package]
name = "spring-websocket"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tokio-tungstenite = "0.28.0"
tokio = { version = "1.0", features = ["full"] }
futures-util = "0.3"
uuid = { version = "1.0", features = ["v4", "serde"] }
dashmap = "6.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tracing = "0.1"
schemars = "1.0.4"
thiserror = "2.0.16"
spring = { version = "0.4.0", path = "../spring" }
spring-web = { version = "0.4.0", path = "../spring-web" }
spring-macros = { version = "0.4.0", path = "../spring-macros" }
axum = { version = "0.8.4", features = ["ws"] }
