[package]
name = "socket-io-example"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring = { path = "../../spring" }
spring-web = { path = "../../spring-web", features = ["socket_io"]}
tokio = { workspace = true, features = ["full", "tracing"] }
