
version: "3"

services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_PASSWORD=xudjf23adj213
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:Z
    ports:
      - 5432:5432
