[package]
name = "job-example"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring = { path = "../../spring" }
spring-job = { path = "../../spring-job", features = ["postgres_storage"] }
spring-web = { path = "../../spring-web" }
spring-sqlx = { path = "../../spring-sqlx", features = [
    "postgres",
    "with-chrono",
] }
tokio = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
